module.exports = {
  severity     : 'warning',
  customSyntax : 'postcss-scss',
  plugins      : ['stylelint-scss'],
  ignoreFiles  : ['**/*.js', '**/*.jsx'],
  rules        : {
    'block-no-empty'                       : true,
    'declaration-block-trailing-semicolon' : 'always',
    'selector-type-no-unknown'             : true,
    'selector-type-case'                   : 'lower',
    'color-no-invalid-hex'                 : true,
    'no-extra-semicolons'                  : true,
    'value-list-comma-newline-after'       : 'always-multi-line',
    'string-quotes'                        : 'single',
    'property-no-vendor-prefix'            : null,
    'rule-empty-line-before'               : null,
    'color-function-notation'              : null,
    'no-invalid-position-at-import-rule'   : null,
    'declaration-colon-space-before'       : 'never',
    'declaration-colon-space-after'        : 'always',
    'block-opening-brace-space-before'     : 'always',
    'block-opening-brace-space-after'      : 'always-single-line',
    'function-comma-space-after'           : 'always',
    'max-empty-lines'                      : 1,
    'comment-empty-line-before'            : 'always',
    'indentation'                          : 2,
    'at-rule-no-unknown'                   : [
      true,
      {
        ignoreAtRules : [
          'at-root',
          'content',
          'debug',
          'each',
          'else',
          'else if',
          'error',
          'extend',
          'font-face',
          'for',
          'function',
          'if',
          'import',
          'include',
          'keyframes',
          'media',
          'mixin',
          'page',
          'return',
          'warn',
          'while',
          'use'
        ],
      }
    ],
    'scss/dollar-variable-pattern'           : null,
    'scss/dollar-variable-empty-line-before' : null,
  },
};
